### ISSUE TITLE
Auxilary Windows remain on top, even when app isn't active 

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#198]
Existing Behavior: 

1. open app
2. dbl click slice.
3. change to different app.
-> notice slice editor remains on top.

desired behavior:
slice editor is behind active app.

**Comment by AaronBehunin** [comment]
For OSX.  Havent tried on other platforms

**Comment by scrgiorgio** [comment]
I know that is ridiculous, but so far this is a Juce limitation with no solution (NOTE: the problem was well known back in 2006!) :

http://www.juce.com/forum/topic/componentaddtodesktop-and-setalwaysontop?page=1

I've tried everything (played with focusGained/focusLost/activeWindowStatusChanged etc etc) but I got tons of random! crashes due to some Juce recursive call.

The only option we have right now is to disable the setAlwaysOnTop.
Or maybe you want to try something different by yourself...
 let me know.

**Comment by cchriste** [comment]
Until the recent new_develop branch came into being, the auxiliary windows were hidden just fine when the app went into the background. You may be thinking of a separate issue, but the issue reported here is in fact new in the past couple months. And I should know since I use the app on OSX every day for years!

**Comment by AaronBehunin** [comment]
Looks like it is fixed on windows

**Comment by scrgiorgio** [comment]
Yes, 
I commented this line:

      //this cause major problems in debugging and with other applications
#if 0
      floating_window->setAlwaysOnTop(true);
#endif

until we find a better solution
