### ISSUE TITLE
x64 OpenGL another bookmark link broken

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#205]
clicking on bookmarks/KAUST/MRI brain gives you a openfile failure error
![brain](https://cloud.githubusercontent.com/assets/10467750/5746376/06366b92-9be4-11e4-88ae-bc4db0559c77.png)

**Comment by scrgiorgio** [comment]
Aaron, we don't have the same bookmarks for every platforms.
So please give me the full url and/or the piece of <dataset...> inside the visus.config.
Also: are you sure the server is up and running? Can you reach it with a telnet on port 80?

**Comment by AaronBehunin** [comment]
i am just using the booksmarks loaded on start up.

It should be under-> bookmarks-> Kaust->MRI Brain

**Comment by scrgiorgio** [comment]
Closing since I don't have enough details.

In general: whenever there is an error about open-dataset failed:

(1) open the visus.config

(2) find the line/lines about that dataset

(3) make sure that the dataset exists and/or is installed on the server

(4) IIF you are sure is all ok and the dataset is still not working, send me the URL (not the alias)
