### ISSUE TITLE
palette is ignored for filtered scalar data (uint8 data + uint8 filter = uint8[2])

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#275]
http://atlantis.sci.utah.edu/mod_visus?dataset=arc_filtered

It ignores any palette settings and displays the equivalent of GreyOpaque.

I don't have a small example right now, but I am trying to use this dataset for an example in a paper.

**Comment by scrgiorgio** [comment]
Try this:

First option) double click on RenderNode and check "Enable gpu palette" (it is not enabled by default since the incoming data is not an atomic field). Then double click on palette and edit it as usual. The RGBA color (applied on the gpu) will be:

    R=palette_R(uint8[0]);
    G=palette_G(uint8[0]);
    B=palette_B(uint8[0]);
    A=palette_A(uint8[1]);

Second option) with a PaletteNode (i.e. a cpu palette) you may have more control about input-outputs.

**Comment by cchriste** [comment]
This is fixed in the current build, which now apparently applies the filter and publishes the uint8 data to the rest of the dataflow rather than publishing the uint8[2] data. This is a perfect solution to the issue.
