### ISSUE TITLE
[new Feature] [Bookmark] server config

### ISSUE THREAD

**Issue by ml639** [sci-visus/visus-issues#342]
There is no way to change the server inside the bookmark right now. Maybe it would be a nice feature that user can modify the server url.

**Comment by scrgiorgio** [comment]
Please explain better. Cannot you just modify the visus.config using a TextEditor?

**Comment by amygooch** [comment]
The point is that we specify each URL to load with Atlantis.

Consider the following:  one day Atlantis went down.  I had to switch it to
Atlanta.  The next time I opened the URL (a week later), Atlanta was not
working and I had to switch them all back to Atlantis,

This is fine for crazy coders like us, but eventually we are trying to
provide these tools for scientist who may not want to query replace or
worse for doctors who would just stare at you.

If we are going to make tools for scientists, we need to enable them to use
the bookmarks in a sensible way.  Opening text editor and doing a query
replace is not good user interaction.  This goes towards other discussions
we've had toward making a UI for the config file.  Which I believe in.

I'm willing to put my fingers to the keypad on this, but so far it is a
feature request and I have a backlog of fun things that must be done first.

my two cents.

Amy

On Tue, Sep 15, 2015 at 2:17 AM, scrgiorgio <notifications@github.com>
wrote:

> Please explain better. Cannot you just modify the visus.config using a
> TextEditor?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/342#issuecomment-140301823>
> .
>



-- 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

(801)-828-5038
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by scrgiorgio** [comment]
ok I'm starting to understand.

But under the following condition: you have a visus.config with N bookmarks (maybe they have the same host, maybe not).

These bookmarks are shown in some Visus menu.

The user click on some bookmark and (if the host is up) the bookmark opens in the Viewer.

How do you 'imagine' the UI to replace the host?

**Comment by mikeliu639** [comment]
One idea is that we can have a section/tab for specifying server
configurations under the settings
​?
​Another idea for dataset group is that group the dataset based on the
host. User can specify new server for different
group
​ of​
 dataset. ​

​This is​
 just an idea.
​There might be some use cases that this might not work that I haven't
thought about..

**Comment by scrgiorgio** [comment]
mmm

assuming that the visus.config uses an alias:

    <alias key='server' value='atlantis.sci.utah.edu' />
    <dataset url="http://$(server)/mod_visus?dataset=rome" />
    <dataset url="http://$(server)/mod_visus?dataset=rome&amp;kdquery=1" />

  <dataset url="http://$(server)/mod_visus?dataset=2kbit1" />
  ...

then we need to add a UI to modify the 'server' alias value.
But with multiple urls is not simple at all.

And to generalize with any combination of url/access is even more difficult
(think about a multiplex access when I can ask some blocks from Server1 and
other blocks from Server2).


2015-09-15 16:17 GMT+02:00 mikeliu639 <notifications@github.com>:

**Comment by cchriste** [comment]
I am going to take the dissenting view on this discussion: how common is
the situation where more than one server will be hosting identical
datasets? Our atlantis/atlanta situation is not a typical case in my mind
(further, those servers have different configs and host different data, and
only happen to have a few datasets in common that just happen to be the
ones we use for testing).

Furthermore, when a server is down in a realistic scenario (e.g. for a web
site), there are fallbacks at the source rather than at the client. Can you
imagine if web browsers had to check google2 if google wasn't responding?

I feel we are spending way too much effort trying to create a fallback for
a possibility for which, were it to occur in practice, we would simply
restart the server, file a bug report, and get on with our lives.

Cameron

**Comment by mikeliu639** [comment]
Initial thought for this feature was that if people at the event really
like it and if ever decide to host the dataset somewhere else. All they
need to do is to change the server config within the app and instead of
downloading an updated version of the app or try to load a different config
file. :) But changing the server configuration may not be the best way to
approach the use case. Maybe we can close this ticket for now if no further
follow up discussion about this yet and we can reopen when we need to
address this use case and maybe we would have a better solution.

Thank you!
Sincerely,
Mike

**Comment by cchriste** [comment]
Changing the server does not magically migrate the data.
They would have to create their own server and visus.config for their users.
I recommend Giorgio's initial suggestion of using an alias. That makes the
visus.config more readable anyway.

**Comment by cchriste** [comment]
Can we close this issue?

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#463
