### ISSUE TITLE
display current min/max in palette

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#345]
This issue was recently noticed by a new user. 

The palette should display the current volume range for scalar fields.

**Comment by scrgiorgio** [comment]
Ok here I will try to explain what is the problem here.

Think about the 'default' situation: we have a Visus palette P that DOES NOT KNOW anything where/when it will be used (99% of the time it will be uploaded/applied on the GPU).

(Case A) P is not used anywhere==nthere is no range to show. No problem so far.

(Case B) P is connected to only one: 
    P->SomeRenderNode. 
    we could come up with something to show up the range.

(Case C) P is connected to more than one node. Example: 
    P->SomeRenderNode1 
    P->SomeRenderNode2
   what is the range to show? AMBIGUITY...

So the real problem is: with the actual implementation the Palette is a 'source' connected (->) to some 'destination' node/nodes, but it's not getting any array in its input. 

In order to show some range I would need the palette to have a 1-and-only-1 (!) array in input.

Maybe we want to have a palette one-to-one with a RenderNode? But then sharing a palette won't be possible anymore.

What do you think?

**Comment by hoangthaiduong** [comment]
I suggest we don't display the range of the data in the palette, but take this part out and put into another component. This component could be thought of as a "palette adapter" that takes input from both a palette and a data source, let the user specify her desired ranges, and outputs a "modified palette" to a render node. Each render node will have a different adapter, and by default an adapter just does nothing.

**Comment by cchriste** [comment]
I like Duong's suggestion quite a bit.

The following issue arises:
A palette can be used to force the range of downstream data. So Duong's adaptor would then need to take into account the (possible) forced range from an upstream palette, the actual data range, and possibly override both.

However, moving back a step, this issue arises because a user benefits in interpreting and forcing the range when she knows the existing range. Therefore, the information is most relevant to be shown in the palette itself. 

It may be reasonable for the palette to show nothing when there are multiple inputs, or to show the union of the inputs.

**Comment by cchriste** [comment]
Also see #259 and #260

**Comment by cchriste** [comment]
This issue came up at LLNL when we were demoing for the climate group.
They want to be able to easily view and change the curent min/max from within the palette.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#462
